{% set name = "yamlprocessor" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/yamlprocessor-{{ version }}.tar.gz
  sha256: e5410865213c2cbbff3986737fdda550ae1d9205a2c23a36d799f6c6eb699760

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - yp-data = yamlprocessor.dataprocess:main
    - yp-schema = yamlprocessor.schemaprocess:main

requirements:
  host:
    - pip
    - python >=3.7
    - pytest-runner
  run:
    - jmespath
    - jsonschema
    - python >=3.7
    - python-dateutil
    - ruamel.yaml

test:
  imports:
    - yamlprocessor
  commands:
    - pip check
    - yp-data --help
    - yp-schema --help
  requires:
    - pip

about:
  home: https://github.com/JCSDA-internal/yamlprocessor
  summary: Process values in YAML files
  description: |
    This project provides a simple utility for working with YAML files, process
    include files, substitute string with variable and date-time values, and
    validate against JSON schema.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://jcsda-internal.github.io/yamlprocessor/
  dev_url: https://github.com/JCSDA-internal/yamlprocessor

extra:
  recipe-maintainers:
    - matthewrmshin
    - KrissyRayD242
