{% set name = "yamlprocessor" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/yamlprocessor-{{ version }}.tar.gz
  sha256: 9c936a0bc569c345e92cc241621b9b4f3dc313fa234cc72b00a33b498e8f1a5c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  entry_points:
    - yp-data = yamlprocessor.dataprocess:main
    - yp-schema = yamlprocessor.schemaprocess:main

requirements:
  host:
    - pip
    - python {{ python_min }}
    - pytest-runner
  run:
    - jmespath
    - jsonschema
    - python >={{ python_min }}
    - python-dateutil
    - ruamel.yaml

test:
  imports:
    - yamlprocessor
  commands:
    - pip check
    - yp-data --help
    - yp-schema --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/JCSDA-internal/yamlprocessor
  summary: Process values in YAML files
  description: |
    This project provides a simple utility for working with YAML files, process
    include files, substitute string with variable and date-time values, and
    validate against JSON schema.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://jcsda-internal.github.io/yamlprocessor/
  dev_url: https://github.com/JCSDA-internal/yamlprocessor

extra:
  recipe-maintainers:
    - matthewrmshin
    - KrissyRayD242
